tipoSiembra(acelga,[directa,almacigo]).
tipoSiembra(chile,[almacigo]).
tipoSiembra(ajo,[directa]).
tipoSiembra(albahaca,[almacigo]).
tipoSiembra(alchachofa,[hijuelos]).
tipoSiembra(anquito,[directa]).
tipoSiembra(apio,[almacigo]).
tipoSiembra(arveja,[directa]).
tipoSiembra(batatas,[almacigo]).
tipoSiembra(berenjena,[almacigo]).
tipoSiembra(berro,[directa]).
tipoSiembra(brocoli,[almacigo]).
tipoSiembra(calabacin,[directa,almacigo]).
tipoSiembra(calabaza,[directa]).
tipoSiembra(canonigo,[directa]).
tipoSiembra(cardos,[directa]).
tipoSiembra(cebollaTemprana,[almacigo]).
tipoSiembra(cebollaTardia,[almacigo]).
tipoSiembra(cebollin,[directa]).
tipoSiembra(ciboulette,[directa]).
tipoSiembra(cilantro,[directa]).
%%coles de bruselas
tipoSiembra(coliflor,[almacigo]).
tipoSiembra(eneldo,[directa]).
tipoSiembra(escarola,[directa]).
tipoSiembra(esparragos,[almacigo]).
tipoSiembra(espinaca,[directa]).
%%tipoSiembra(estragon,[]).
tipoSiembra(fresas,[estolon]).
tipoSiembra(garbanzos,[directa]).
tipoSiembra(haba,[directa]).
tipoSiembra(hinojo,[almacigo]).
tipoSiembra(lavanda,[directa]).
tipoSiembra(lechuga,[directa,almacigo]).
tipoSiembra(maiz,[directa]).
tipoSiembra(manzanilla,[directa]).
tipoSiembra(mejorana,[directa]).
tipoSiembra(menta,[directa,almacigo]).
tipoSiembra(melisa,[almacigo]).
tipoSiembra(melon,[directa,almacigo]).
tipoSiembra(mostaza,[directa,almacigo]).

%%Profundidad de siembra en centimetros
profundidad(acelga,2).
profundidad(chile,'0.6').
profundidad(albahaca,7).
profundidad(alchachofa,4).
profundidad(anquito,'2.5').
profundidad(apio,1).
profundidad(arveja,3).
profundidad(batatas,8).
profundidad(berenjena,1).
profundidad(berro,x).
profundidad(brocoli,'1.5').
profundidad(calabacin,2).
profundidad(calabaza,4).
profundidad(canonigo,'0.5').
profundidad(cardos,2).
profundidad(cebollaTemprana,1).
profundidad(cebollaTardia,1).
profundidad(cebollin,1).
profundidad(ciboulette,'0.5').
profundidad(cilantro,1).
profundidad(coliflor,1).
profundidad(eneldo,1).
profundidad(escarola,1).
profundidad(esparrago,5).
profundidad(espinaca,2).
profundidad(estragon,1).
profundidad(fresas,8).
profundidad(garbanzos,5).
profundidad(haba,5).
profundidad(hinojo,2).
profundidad(lavanda,1).
profundidad(lechuga,1).
profundidad(maiz,5).
profundidad(manzanilla,'1.5').
profundidad(mejorana,'0.5').
profundidad(menta,1).
profundidad(melisa,1).
profundidad(melon,4).
profundidad(mostaza,'1.2').

%%distancia en cm(plantas,hileras)

distancia(acelga,20,60).
distancia(chile,25,45).
distancia(ajo,8,30).
distancia(albahaca,25,60).
distancia(alchachofa,60,75).
distancia(anquito,10,180).
distancia(apio,30,70).
distancia(arveja,50,70).
distancia(batatas,40,80).
distancia(berenjena,50,70).
distancia(berro,10,10).
distancia(brocoli,45,75).
distancia(calabacin,80,100).
distancia(calabaza,120,180).
distancia(canonigo,10,20).
distancia(cardos,80,100).
distancia(cebollaTemprana,15,35).
distancia(cebollaTardia,15,35).
distancia(cebollin,30,60).
distancia(ciboulette,5,20).
distancia(cilantro,12,30).
distancia(coliflor,50,80).
distancia(eneldo,30,30).
distancia(escarola,10,30).
distancia(esparrago,7,30).
distancia(espinaca,15,30).
distancia(estragon,30,40).
distancia(fresas,30,50).
distancia(garbanzos,40,40).
distancia(haba,30,70).
distancia(hinojo,30,70).
distancia(lavanda,30,40).
distancia(lechuga,20,30).
distancia(maiz,30,70).
distancia(manzanilla,15,25).
distancia(mejorana,25,25).
distancia(menta,25,25).
distancia(melisa,30,30).
distancia(melon,150,200).
distancia(mostaza,30,40).


asociar(acelga,[lechuga,coles,coliflor]).
asociar(chile,[berenjena,coles,albahaca]).
asociar(ajo,[lechuga,hinojo]).
asociar(albahaca,[pepino,tomate]).
asociar(alchachofa,[lechuga]).
asociar(anquito,[maiz,acelga]).
asociar(apio,[lechuga]).
asociar(arveja,[zanahoria,lechuga]).
asociar(batatas,[nada]).
asociar(berenjena,[lechuga,coliflor]).
asociar(berro,[no]).
asociar(brocoli,[espinaca]).
asociar(calabacin,[maiz,acelga]).
asociar(calabaza,[maiz,lechuga]).
asociar(canonigo,[zanahoria,coles,lechuga]).
asociar(cardos,[haba]).
asociar(cebollaTemprana,[lechuga,coliflor]).
asociar(cebollaTardia,[zanahoria,lechuga,fresas,coles,tomate]).
asociar(cebollin,[zanahoria]).
asociar(ciboulette,[zanahoria]).
asociar(cilantro,[no]).
asociar(coliflor,[lechuga,apio,zanahoria]).
asociar(eneldo,[coles,calabaza]).
asociar(escarola,[lechuga,tomate]).
asociar(esparrago,[lechuga,tomate]).
asociar(espinaca,[coliflor,brocoli]).
asociar(estragon,[no]).
asociar(fresas,[ajo,espinaca,lechuga]).
asociar(garbanzos,[no]).
asociar(haba,[zanahoria,coliflor]).
asociar(hinojo,[no]).
asociar(lavanda,[no]).
asociar(lechuga,[acelga,zanahoria]).
asociar(maiz,[acelga]).
asociar(manzanilla,[coles]).
asociar(mejorana,[todo]).
asociar(menta,[coles,lechuga]).
asociar(melisa,[todo]).
asociar(melon,[lechuga,maiz]).
asociar(mostaza,[acelga]).






(acelga,).
(chile,).
(ajo,).
(albahaca,).
(alchachofa,).
(anquito,).
(api,).
(arveja,).
(batatas,).
(berenjena,).
(berro,).
(brocoli,).
(calabacin,).
(calabaza,).
(canonigo,).
(cardos,).
(cebollaTemprana,).
(cebollaTardia,).
(cebollin,).
(ciboulette,).
(cilantro,).
(coliflor,).
(eneldo,).
(escarola,).
(esparrago,).
(espinaca,).
(estragon,).
(fresas,).
(garbanzos,).
(haba,).
(hinojo,).
(lavanda,).
(lechuga,).
(maiz,).
(manzanilla,).
(mejorana,).
(menta,).
(melisa,).
(melon,).
(mostaza,).

